version: '3.4'

services:

  frontend:
    image: tcode/frontend
    build:
      context: ./frontend
    # Uncoment this if you want test some features
    #volumes:
      #- ./frontend/src:/app/src
    ports:
      - 3000:3000
    

  backend:
    image: tcode/backend
    build:
      context: ./backend
    # Uncoment this if you want test some features
    #volumes:
      #- ./backend:/app
    depends_on:
      - frontend
    ports:
      - 5000:5000
