version: '3.4'

services:

  frontend:
    image: tcode/frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    

  backend:
    image: tcode/backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    ports:
      - 5000:5000